# # This is a basic workflow to help you get started with Actions
# name: SSH
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup upterm session
#       uses: lhotari/action-upterm@v1
#       with:
#         ## limits ssh access and adds the ssh public key for the user which triggered the workflow
#         limit-access-to-actor: true
#         ## limits ssh access and adds the ssh public keys of the listed GitHub users
#         limit-access-to-users: ${{secrets.sshpublickey01}}
        
# name: SSH Server
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1

#      - name: Try Build
#        run: ./not-exist-file.sh it bloke build

#      - name: Start SSH via Ngrok
#        if: ${{ failure() }}
#        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#        env:
#         # After sign up on the https://ngrok.com/
#         # You can find this token here: https://dashboard.ngrok.com/get-started/setup
#         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

#         # This password you will use when authorizing via SSH 
#         USER_PASS: ${{ secrets.USER_PASS }}

#      - name: Don't kill instace
#        if: ${{ failure() }}
#        run: sleep 10h 
#        # Prevent to killing instance after failure


# name: CI
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup upterm session
#       uses: lhotari/action-upterm@v1

# name: CI
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3

name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
